namespace SerenCluster.Configuration
{

    /// <summary>
    /// Configuration for one Jetson (or one local agent) the RuntimeHost talks to.
    /// </summary>
    public sealed class JetsonNodeOptions
    {
        /// <summary>
        /// Friendly name for this node - appears in logs, dashboards, and route
        /// decisions. Must be unique across <see cref="ClusterOptions.Nodes"/>.
        /// Examples: <c>xavier32gb</c>, <c>nano</c>, <c>localhost</c>.
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Base URL of the agent on this node. Includes scheme, host, port -
        /// no trailing slash, no path. Example: <c>http://192.168.0.102:7777</c>.
        /// </summary>
        public string AgentUrl { get; set; } = string.Empty;

        /// <summary>
        /// Bearer token for authenticating to this node's agent. Generated by
        /// <c>seren-secrets.sh</c> on the Jetson side; copy the value here.
        /// </summary>
        /// <remarks>
        /// This file should be <c>chmod 600</c> and not committed to git. A
        /// future revision may move tokens to a separate secrets file or env
        /// vars; for now keeping them inline is simpler and matches what
        /// <c>RunRuntimeOptions</c> already did.
        /// </remarks>
        public string AgentToken { get; set; } = string.Empty;

        /// <summary>
        /// Capabilities this node is preferred to serve. When multiple nodes
        /// have the same service installed, the one listing it here wins.
        /// </summary>
        /// <remarks>
        /// Routing policy is "preferred-list order" - the first configured node
        /// listing a capability gets every request for it until it goes offline,
        /// then fall-through to the next configured node that has the service
        /// installed (per its agent's manifest). Round-robin and stickiness are
        /// later optimizations.
        /// </remarks>
        public List<string> PreferredFor { get; set; } = [];

        /// <summary>
        /// Absolute path on the node's filesystem where the RuntimeHost should
        /// deliver <c>seren-agent.tar.gz</c> during an agent update push.
        /// The <c>seren-agent-update.sh</c> script must live in the same
        /// directory.
        ///
        /// Example: <c>/home/seren/seren-install</c>
        ///
        /// Leave empty to exclude this node from agent-update operations.
        /// </summary>
        public string AgentUpdatePath { get; set; } = string.Empty;

        /// <summary>
        /// Signals which node runs the RuntimeHost. Only one node should have 
        /// this true; if multiple nodes have this true, the first one in the 
        /// config wins and the others are ignored.
        /// </summary>
        public bool IsHost { get; set; } = false;

        /// <summary>
        /// Optional affectionate name for this node, used in narrative output
        /// (the LLM's self-context, friendly UI labels, dashboard hover tips).
        /// Distinct from <see cref="Name"/> which is the routing identifier.
        ///
        /// If unset, narrative output falls back to <see cref="Name"/>. Set it
        /// to something easy to say in conversation - "Bear", "Fox", "Beast".
        /// The 32-and-16 Sharpie marks on Chad's Xavier heatsinks are the
        /// physical-world precedent for this field.
        /// </summary>
        public string Nickname { get; set; } = string.Empty;
    }

}
